# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/hertz/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/hertz

PRODUCT_COPY_FILES += \
    vendor/amlogic/hertz/proprietary/vendor/etc/bluetooth//BCM4345C0.hcd:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth//BCM4345C0.hcd \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/config.txt \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag.bin \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag_apsta.bin \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/fw_bcm43455c0_ag_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43455c0_ag_p2p.bin \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/fw_bcm43456c5_ag.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43456c5_ag.bin \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/fw_bcm43456c5_ag_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/fw_bcm43456c5_ag_apsta.bin \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/nvram_ap6255.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/nvram_ap6255.txt \
    vendor/amlogic/hertz/proprietary/vendor/etc/wifi/6255/nvram_ap6256.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/6255/nvram_ap6256.txt \
    vendor/amlogic/hertz/proprietary/vendor/usr/keylayout//Vendor_0001_Product_0001.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout//Vendor_0001_Product_0001.kl
PRODUCT_COPY_FILES += \
    vendor/amlogic/hertz/proprietary/vendor/etc/tvconfig/pq/pq.db:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq.db \
    vendor/amlogic/hertz/proprietary/vendor/etc/tvconfig/pq/pq_default.ini:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq_default.ini \
    vendor/amlogic/hertz/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/amlogic/hertz/proprietary/vendor/lib/hw/gralloc.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.amlogic.so \
    vendor/amlogic/hertz/proprietary/vendor/lib/hw/hwcomposer.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.amlogic.so
